plugins {
    id 'java-library'
}

dependencies {
    implementation project(':base')
    implementation 'org.springframework.boot:spring-boot-starter'
    implementation(libs.telegrambots.client)
    implementation(libs.telegrambots.springboot.longpolling.starter)
    implementation(libs.commonmark.java)
    implementation(libs.commonmark.ext.gfm.strikethrough)

    implementation 'io.projectreactor:reactor-core:3.6.0'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}