name: CI + Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Deploy Webhook
        run: |
          curl -X POST https://deploy.devlab.dpdns.org \
          -H "Authorization: Bearer ${{ secrets.DEPLOY_TOKEN }}"
